service:
  build: .
  dockerfile: Dockerfile
  command: local
  ports:
    - 8000:8000
    - 3000:3000
  volumes:
    - $PWD/estate:/usr/local/service/estate
    - $PWD/webpack:/usr/local/service/webpack
    - $PWD/scripts/local.sh:/usr/bin/local
    - /var/run/docker.sock:/var/run/docker.sock
    - /tmp:/tmp
  environment:
    - "DEBUG=True"
    - "DATABASE_URL=postgres://postgres:estate@postgres:5432/estate"
    - "TERRAFORM_DOCKER_IMAGE=lakshminp/terraform:0.11.10"
  links:
    - postgres:postgres
    - vault:vault

postgres:
  image: postgres:9.5
  environment:
    - "POSTGRES_PASSWORD=estate"
    - "POSTGRES_DB=estate"

vault:
  image: vault:0.7.3
  environment:
    - "VAULT_DEV_ROOT_TOKEN_ID=estate"
    - "VAULT_TOKEN=estate"
    - "VAULT_ADDR=http://127.0.0.1:8200"
  cap_add:
    - IPC_LOCK
  ports:
    - 8200:8200
